uriyyo/fastapi-pagination

fastapi_pagination/ext/django.py
tests/ext/test_django.py

🔧 Update django integration

---

examples/pagination_ormar.py

@collerek Could you review this? Was this originally a copy-paste error?

Fix ormar example uvicorn invocation

---

fastapi_pagination/__init__.py
fastapi_pagination/api.py
fastapi_pagination/links/__init__.py
fastapi_pagination/links/bases.py
fastapi_pagination/links/default.py
fastapi_pagination/links/limmit_offset.py
pytest.ini
tests/test_api.py
tests/test_links.py

Add page links

---

fastapi_pagination/ext/sqlalchemy.py

Add ability to serialize not only models

---

fastapi_pagination/__init__.py

Add missed __all__ to __init__

---

fastapi_pagination/iterables.py
tests/base.py
tests/test_iterables.py

Add ability to paginate iterables

---

fastapi_pagination/default.py
fastapi_pagination/links/default.py
tests/base.py
tests/test_bases.py
tests/test_links.py

🐛  Use 1 as a default number for page

---

docs/customization.md

Update docs for page customisation

---

fastapi_pagination/api.py

Hide warning when importing pagination_params

---

README.md
examples/pagination_piccolo.py
fastapi_pagination/ext/piccolo.py
poetry.lock
pyproject.toml
tests/ext/test_piccolo.py

🔧  Add piccolo integration

---

.github/workflows/test.yml
fastapi_pagination/ext/sqlalchemy_future.py
poetry.lock
pyproject.toml
tests/ext/test_async_sqlalchemy.py
tests/ext/test_sqlalchemy_future.py

🔧 Add support for new sqlalchemy query syntax

---

poetry.lock
pyproject.toml

🔧 Relax dependencies versions

---

.github/workflows/test.yml
README.md
fastapi_pagination/ext/sqlmodel.py
pyproject.toml
tests/ext/test_sqlmodel.py

🔧 Add sqlmodel integration

---

.github/workflows/test.yml
README.md
examples/pagination_motor.py
fastapi_pagination/ext/motor.py
poetry.lock
pyproject.toml
pytest.ini
tests/conftest.py
tests/ext/test_motor.py

Add asynchronous MongoDB integration through Motor

🔧 Add Motor integration

---

.github/workflows/test.yml
fastapi_pagination/ext/tortoise.py
poetry.lock
tests/ext/test_tortoise.py

🔧   Add ability to prefetch related models for tortoise

---

fastapi_pagination/ext/motor.py
tests/ext/test_motor_aggregate.py

Had some problems implementing the tests. Perhaps you could give me some instructions here.

adds support for mongo paginate pipelines

---

fastapi_pagination/ext/async_sqlmodel.py
fastapi_pagination/limit_offset.py

Thanks for this awesome package. In this Pull request, I have added:
1.- An ext for async sqlmodel configuration

Add async support for sqlmodel

---

docs/advanced.md

Simple typo fix for LimitOffsetPage data schema

Update advanced documentation

---

README.md
fastapi_pagination/ext/pymongo.py
tests/ext/test_pymongo.py

Hey @uriyyo,
awesome repo you got here.
Because I couldn't find a pymongo integration I simply created one by myself.
As far as I've seen it there are no contribution guidelines, so I hope this PR is ok.
Let me now what you think.
Thanks in advance.

Add pymongo integration

---

docs/index.md
docs/integrations.md
mkdocs.yml

When I was using this library for the first time, I completely missed the integrations section of the documentation, I thought it might be helpful to have an integrations page of the documentation to make it a little clearer.
I've never used any of the integrations apart from the SQLAlchemy one so I fleshed out the SQLAlchemy integration section a little bit but left the other ones with just a link to the examples.

SQLAlchemy integration documentation

---

fastapi_pagination/ext/async_sqlalchemy.py
fastapi_pagination/ext/async_sqlmodel.py
fastapi_pagination/ext/sqlalchemy.py
fastapi_pagination/ext/sqlalchemy_future.py
fastapi_pagination/ext/sqlmodel.py
fastapi_pagination/types.py
tests/ext/test_sqlalchemy_row_number_pagination.py

Add ability to row-numer based pagination

---

fastapi_pagination/ext/beanie.py
poetry.lock
pyproject.toml
tests/ext/test_beanie.py

🎅 Add beanie integration

---

fastapi_pagination/bases.py
fastapi_pagination/cursor.py
fastapi_pagination/types.py

Add ability to use bytes as cursor and encode cursor

---

fastapi_pagination/api.py
fastapi_pagination/ext/sqlalchemy.py
poetry.lock

Make sqlakeyset module optional

---

fastapi_pagination/ext/async_sqlalchemy.py
fastapi_pagination/ext/async_sqlmodel.py
fastapi_pagination/ext/sqlalchemy_future.py
fastapi_pagination/ext/sqlmodel.py

Add ability to have non-unique sqlalchemy results

---

fastapi_pagination/ext/beanie.py

Add ability to pass fetch_links to beanie query

---

examples/pagination_beanie.py

Hello, I am very grateful for your amazing work.
Since there is no example of Beanie, I added a simple example.
It was written to be consistent with other files as much as possible.
Please review and approve when you are comfortable :)
Best regards,

Add beanie example

---

fastapi_pagination/ext/databases.py

Fix databases deprecated record usage

---

fastapi_pagination/ext/async_sqlalchemy.py
fastapi_pagination/ext/async_sqlmodel.py
fastapi_pagination/ext/asyncpg.py
fastapi_pagination/ext/beanie.py
fastapi_pagination/ext/cassandra.py
fastapi_pagination/ext/databases.py
fastapi_pagination/ext/django.py
fastapi_pagination/ext/gino.py
fastapi_pagination/ext/mongoengine.py
fastapi_pagination/ext/motor.py
fastapi_pagination/ext/orm.py
fastapi_pagination/ext/ormar.py
fastapi_pagination/ext/piccolo.py
fastapi_pagination/ext/pony.py
fastapi_pagination/ext/pymongo.py
fastapi_pagination/ext/sqlalchemy.py
fastapi_pagination/ext/sqlalchemy_future.py
fastapi_pagination/ext/sqlmodel.py
fastapi_pagination/ext/tortoise.py
fastapi_pagination/iterables.py
fastapi_pagination/paginator.py

Return Any from paginate functions

---

examples/pagination_async_sqlalchemy.py
fastapi_pagination/api.py
fastapi_pagination/ext/async_sqlalchemy.py
fastapi_pagination/ext/async_sqlmodel.py
fastapi_pagination/ext/asyncpg.py
fastapi_pagination/ext/beanie.py
fastapi_pagination/ext/cassandra.py
fastapi_pagination/ext/databases.py
fastapi_pagination/ext/django.py
fastapi_pagination/ext/gino.py
fastapi_pagination/ext/mongoengine.py
fastapi_pagination/ext/motor.py
fastapi_pagination/ext/orm.py
fastapi_pagination/ext/ormar.py
fastapi_pagination/ext/piccolo.py
fastapi_pagination/ext/pony.py
fastapi_pagination/ext/pymongo.py
fastapi_pagination/ext/sqlalchemy.py
fastapi_pagination/ext/sqlalchemy_future.py
fastapi_pagination/ext/sqlmodel.py
fastapi_pagination/ext/tortoise.py
fastapi_pagination/iterables.py
fastapi_pagination/paginator.py
fastapi_pagination/types.py
fastapi_pagination/utils.py
tests/test_api.py
tests/test_paginator.py

Add items transformer

---

fastapi_pagination/ext/motor.py
tests/ext/test_motor.py

Add ability to sort with motor ext

---

fastapi_pagination/ext/sqlalchemy.py

Add ability to use unique with `sqlalchemy.orm.Query`

---

fastapi_pagination/api.py

We added docstring for "create_page" method

Added docstring for "create_page" method

---

fastapi_pagination/bases.py

Initial pydantic v2 support

---

fastapi_pagination/ext/sqlalchemy.py

Fix issue with old `sqlalchemy.orm.Query` usage

---

fastapi_pagination/bases.py
fastapi_pagination/links/bases.py
fastapi_pagination/links/default.py
fastapi_pagination/links/limit_offset.py

https://github.com/uriyyo/fastapi-pagination/issues/714#issuecomment-1632930255

Remove usage of deprecated pydantic v1 API

---

fastapi_pagination/ext/pymongo.py

https://github.com/uriyyo/fastapi-pagination/issues/649

Add pymongo sort

---

fastapi_pagination/bases.py

https://github.com/uriyyo/fastapi-pagination/issues/714#issuecomment-1663333818

fixed warnings with GenericModel

---

fastapi_pagination/api.py
tests/test_api.py

Fix issue with pydantic v2 params validation

---

fastapi_pagination/links/default.py
tests/test_links.py

Fix issue with links Page revalidation

---

fastapi_pagination/links/bases.py

https://docs.pydantic.dev/latest/migration/#changes-to-pydanticfield

Fix issue where Pydantic2 would raise warnings when arbitrary keywords are set.

---

fastapi_pagination/api.py

Update body_field when patch route

---

fastapi_pagination/ext/piccolo.py

Fix issue with order by raise 500 for piccolo ext

---

fastapi_pagination/ext/sqlalchemy.py

Add ability to use `async_scoped_session`

---

fastapi_pagination/ext/motor.py
tests/ext/test_motor.py

Update motor sorting 

---

fastapi_pagination/bases.py

Remove usage of deprecated pydantic v2 field

---

fastapi_pagination/api.py

Add support for pydantic v2 aliases

---

pyproject.toml

Hi!
https://sqlmodel.tiangolo.com/release-notes/
2 new minor updates of sqlmodel were released

Bump sqlmodel version

---

fastapi_pagination/ext/pymongo.py

Fix issue with default value for pymongo

---

fastapi_pagination/cursor.py
tests/test_cursor.py

Raise 400 error on invalid cursor value

---

fastapi_pagination/default.py
fastapi_pagination/links/default.py
tests/test_bases.py

Fix issue with zero size

---

.github/workflows/test.yml
pyproject.toml

Add python 3.12 official support

---

fastapi_pagination/ext/piccolo.py

Fix piccolo issue when filter by foreign field

---

fastapi_pagination/bases.py
fastapi_pagination/utils.py
tests/test_bases.py

Auto wrap params values into query

---

fastapi_pagination/ext/sqlalchemy.py

Add better exc message for non-hashable rows

---

docs/tutorials_advanced/customization.md

Fix a typo in documentation for CustomizedPage

---

.pre-commit-config.yaml
fastapi_pagination/ext/asyncpg.py
fastapi_pagination/ext/databases.py
fastapi_pagination/ext/sqlalchemy.py
tests/base.py
tests/ext/test_sqlalchemy_text.py

Add ability to paginate raw queries

---

fastapi_pagination/api.py
tests/test_invalid_usage.py

#362 - https://github.com/uriyyo/fastapi-pagination/issues/362#issuecomment-2064905986

Improve resolve_params exc message

---

.github/workflows/test.yml
fastapi_pagination/ext/odmantic.py
tests/base.py
tests/ext/test_asyncpg.py
tests/ext/test_beanie.py
tests/ext/test_bunnet.py
tests/ext/test_mongoengine.py
tests/ext/test_motor.py
tests/ext/test_motor_aggregate.py
tests/ext/test_odmantic.py
tests/ext/test_ormar.py
tests/ext/test_pymongo.py
tests/ext/utils.py
tests/schemas.py

Add odmantic integration

---

fastapi_pagination/ext/databases.py

Fix issue with databases + sqlalchemy 2.0

---

fastapi_pagination/async_paginator.py
fastapi_pagination/utils.py
tests/test_async_paginator.py

Add ability to use async function with async_paginator

---

examples/pagination_sqlalchemy.py
fastapi_pagination/ext/sqlalchemy.py
tests/ext/test_sqlalchemy_from_statement.py

Add support for sqlalchemy from statement

---

fastapi_pagination/ext/sqlalchemy.py

https://github.com/uriyyo/fastapi-pagination/issues/1256#issuecomment-2343678499

Fix issue with sqlalchemy imports for Gino ext

---

tests/ext/test_sqlalchemy.py

Add tests for sqlachemy scalar unwrap logic

---

fastapi_pagination/ext/sqlalchemy.py
tests/ext/test_sqlalchemy.py

Fix issue with SQLAlchemy scalar select detection

---

fastapi_pagination/ext/sqlalchemy.py

Fix issue when select model with single field

---

fastapi_pagination/ext/sqlalchemy.py
pyproject.toml

Add NotImplementedError to ignored exc

---

fastapi_pagination/ext/sqlalchemy.py
tests/ext/test_sqlalchemy.py

Add support for CompoundSelect

---

fastapi_pagination/ext/sqlmodel.py

Add BaseSelect type hint for SQLModel paginate

---

fastapi_pagination/ext/sqlalchemy.py

Fix issue with sqlalchemy select with session.query

---

docs/customization/customizers/use_quoted_cursor.md
fastapi_pagination/cursor.py
fastapi_pagination/customization.py
tests/ext/test_sqlalchemy_cursor.py
tests/test_cursor.py
tests/test_customization.py

Add ability to quote/unquote cursor

---

fastapi_pagination/cursor.py
tests/test_cursor.py

Fix issue with 500 error on invalid cursor value

---

fastapi_pagination/api.py
fastapi_pagination/bases.py
fastapi_pagination/cursor.py
fastapi_pagination/customization.py
fastapi_pagination/default.py
fastapi_pagination/errors.py
fastapi_pagination/iterables.py
fastapi_pagination/limit_offset.py
fastapi_pagination/links/default.py
scripts/ci-test.sh
tests/test_api.py
tests/test_bases.py
tests/test_customization.py
tests/test_invalid_usage.py

Connect params to page

---

fastapi_pagination/ext/pymongo.py
tests/ext/test_pymongo.py

Add async pymongo integration

---

fastapi_pagination/ext/pymongo.py
tests/ext/test_pymongo.py
tests/ext/test_pymongo_aggregate.py
uv.lock

Add pymongo aggregate funcs
